/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.hospital.forms;

/**
 *
 * @author Lime
 */
public class Acasa extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Acasa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        reg_pacient = new javax.swing.JButton();
        reg_diagnostic = new javax.swing.JButton();
        reg_istoric = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        vizualizare = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 531));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\DOWNLOAD_OFFICIAL\\Aplicatie_pt_examen\\Images\\med.png")); // NOI18N

        reg_pacient.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        reg_pacient.setText("Inregistrare Pacient");
        reg_pacient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        reg_pacient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reg_pacient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_pacientActionPerformed(evt);
            }
        });

        reg_diagnostic.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        reg_diagnostic.setText("Inregistrare diagnostic");
        reg_diagnostic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        reg_diagnostic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reg_diagnostic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_diagnosticActionPerformed(evt);
            }
        });

        reg_istoric.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        reg_istoric.setText("Programari");
        reg_istoric.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        reg_istoric.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reg_istoric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_istoricActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 153, 51));
        logout.setText("Delogare");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        vizualizare.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        vizualizare.setText("Vizualizare & Actualizare Pacienti");
        vizualizare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        vizualizare.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vizualizare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vizualizareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reg_diagnostic, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vizualizare, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addComponent(logout))
                                .addComponent(reg_pacient, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(14, 14, 14))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(reg_istoric, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(reg_pacient)
                .addGap(51, 51, 51)
                .addComponent(vizualizare)
                .addGap(51, 51, 51)
                .addComponent(reg_diagnostic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(reg_istoric)
                .addGap(69, 69, 69)
                .addComponent(logout)
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("HOME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 17, -1, 39));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\DOWNLOAD_OFFICIAL\\Aplicatie_pt_examen\\Images\\2.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 540, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reg_pacientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_pacientActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Inregistrare_pacient().setVisible(true);
    }//GEN-LAST:event_reg_pacientActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
            // TODO add your handling code here:
           setVisible(false);
           new LoginForm().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void reg_diagnosticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_diagnosticActionPerformed
        // TODO add your handling code here:
         setVisible(false);
         new Inregistrare_diagnostic().setVisible(true);

    }//GEN-LAST:event_reg_diagnosticActionPerformed

    private void vizualizareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vizualizareActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new vizualizare().setVisible(true);
    }//GEN-LAST:event_vizualizareActionPerformed

    private void reg_istoricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_istoricActionPerformed
        // TODO add your handling code here:
        setVisible(false);
         new programari().setVisible(true);
    }//GEN-LAST:event_reg_istoricActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton reg_diagnostic;
    private javax.swing.JButton reg_istoric;
    private javax.swing.JButton reg_pacient;
    private javax.swing.JButton vizualizare;
    // End of variables declaration//GEN-END:variables
}
