/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.hospital.forms;

import hospital.hospital.clase.DBClass;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Lime
 */
public class Inregistrare_pacient extends javax.swing.JFrame {

    /**
     * Creates new form Inregistrare_pacient
     */
    DBClass db = new DBClass();
    public Inregistrare_pacient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PBoli = new javax.swing.JTextField();
        Pid = new javax.swing.JTextField();
        Pnume = new javax.swing.JTextField();
        PAdresa = new javax.swing.JTextField();
        PTelefon = new javax.swing.JTextField();
        PVarsta = new javax.swing.JTextField();
        PGrupas = new javax.swing.JTextField();
        sex = new javax.swing.JComboBox<>();
        Inchidere = new javax.swing.JButton();
        Salvare1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 531));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Boli Cronice");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ID_Pacient");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nume si Prenume");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 170, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Adresa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Telefon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Varsta");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 170, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Sex");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 170, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Grupa sanguina");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 170, -1));

        PBoli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PBoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBoliActionPerformed(evt);
            }
        });
        getContentPane().add(PBoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 410, -1));

        Pid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(Pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 410, -1));

        Pnume.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(Pnume, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 410, -1));

        PAdresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PAdresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAdresaActionPerformed(evt);
            }
        });
        getContentPane().add(PAdresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 410, -1));

        PTelefon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTelefonActionPerformed(evt);
            }
        });
        getContentPane().add(PTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 410, -1));

        PVarsta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PVarsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PVarstaActionPerformed(evt);
            }
        });
        getContentPane().add(PVarsta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 410, -1));

        PGrupas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PGrupas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PGrupasActionPerformed(evt);
            }
        });
        getContentPane().add(PGrupas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 410, -1));

        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculin", "Feminin" }));
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 410, -1));

        Inchidere.setText("Inchidere");
        Inchidere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InchidereActionPerformed(evt);
            }
        });
        getContentPane().add(Inchidere, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, -1));

        Salvare1.setText("Salvare");
        Salvare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvare1ActionPerformed(evt);
            }
        });
        getContentPane().add(Salvare1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Inregistrare Pacient");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\0002021\\TAP\\hospital\\pastile.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PBoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBoliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PBoliActionPerformed

    private void PAdresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAdresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PAdresaActionPerformed

    private void PTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PTelefonActionPerformed

    private void PVarstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PVarstaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PVarstaActionPerformed

    private void PGrupasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PGrupasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PGrupasActionPerformed

    private void Salvare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvare1ActionPerformed
            // TODO add your handling code here:
            if(Pid.getText().equals("") || Pnume.getText().equals("")||PAdresa.getText().equals("")||PTelefon.getText().equals("") ||PVarsta.getText().equals("")|| PBoli.getText().equals("")||PGrupas.getText().equals("") )
            {
                JOptionPane.showMessageDialog(null,"Introdu toate datele corect!");
            }
            else
            {
                
            
            String patientid = Pid.getText();
            String pname = Pnume.getText();
            String padresa = PAdresa.getText();
            String ptelefon = PTelefon.getText();
            String pvarsta = PVarsta.getText();
            String psex = (String) sex.getSelectedItem();
            String pgrupas = PGrupas.getText();
            String pboli = PBoli.getText();
            
            try{
                db.execute("insert into inregistrare_pacient values (?,?,?,?,?,?,?,?)", patientid,pname,padresa,ptelefon,pvarsta,psex,pgrupas,pboli);
                JOptionPane.showMessageDialog(null,"Pacient adaugat cu succes");
                setVisible(false);
                new Acasa().setVisible(true);
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Eroare conexiune");
            }
           }
    }//GEN-LAST:event_Salvare1ActionPerformed

    private void InchidereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InchidereActionPerformed
   setVisible(false);
   new Acasa().setVisible(true);
   // TODO add your handling code here:
    }//GEN-LAST:event_InchidereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inregistrare_pacient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inregistrare_pacient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inregistrare_pacient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inregistrare_pacient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inregistrare_pacient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inchidere;
    private javax.swing.JTextField PAdresa;
    private javax.swing.JTextField PBoli;
    private javax.swing.JTextField PGrupas;
    private javax.swing.JTextField PTelefon;
    private javax.swing.JTextField PVarsta;
    private javax.swing.JTextField Pid;
    private javax.swing.JTextField Pnume;
    private javax.swing.JButton Salvare1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> sex;
    // End of variables declaration//GEN-END:variables
}
