/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.hospital.forms;
import  hospital.hospital.forms.Acasa;
import hospital.hospital.clase.DBClass;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;

import hospital.hospital.clase.DBClass;


/**
 *
 * @author Lime
 */
public class vizualizare extends javax.swing.JFrame {

       private static final String username="root";
       private static final String password="1234";
       private static final String dataConn="jdbc:mysql://localhost:3306/hospital";
       
       Connection sqlConn = null;
       PreparedStatement pst = null;
       ResultSet rs=null;
       int q,i,id,deleteItem;
    DBClass db = new DBClass();
    public vizualizare() {
        initComponents();
    }
    
//  =============================FUNCTIE=======================================
    public void upDateDB()
    {
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn=DriverManager.getConnection(dataConn,username,password);
            pst=sqlConn.prepareStatement("select * from inregistrare_pacient");
            rs =pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel) tabel.getModel();
                    RecordTable.setRowCount(0);
            while(rs.next())
            {
                Vector columnData =new Vector();
                for(i=1;i<=q;i++)
                {
                    columnData.add(rs.getString("Pid"));
                    columnData.add(rs.getString("pnume"));
                    columnData.add(rs.getString("padresa"));
                    columnData.add(rs.getString("ptelefon"));
                    columnData.add(rs.getString("pvarsta"));
                    columnData.add(rs.getString("psex"));
                    columnData.add(rs.getString("pgrupas"));
                    columnData.add(rs.getString("pboli"));
                }
                RecordTable.addRow(columnData);
            }
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Print = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        inapoi = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jpboli = new javax.swing.JTextField();
        jpid = new javax.swing.JTextField();
        jpnume = new javax.swing.JTextField();
        jpadresa = new javax.swing.JTextField();
        jptelefon = new javax.swing.JTextField();
        jpvarsta = new javax.swing.JTextField();
        jpgrupas = new javax.swing.JTextField();
        sex = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 531));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Print.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Print.setText("PRINT");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel1.add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 80, -1));

        Reset.setBackground(new java.awt.Color(204, 204, 255));
        Reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel1.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, -1));

        Delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 80, -1));

        inapoi.setBackground(new java.awt.Color(255, 204, 51));
        inapoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inapoi.setText("INAPOI");
        inapoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inapoiActionPerformed(evt);
            }
        });
        jPanel1.add(inapoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        Update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 180, 210));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pid", "pnume", "padresa", "ptelefon", "pvarsta", "psex", "pgrupas", "pboli"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 560, 230));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("pboli");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Pid");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("pnume");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("padresa");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("ptelefon");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("pvarsta");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 70, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("psex");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 70, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("pgrupas");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 70, -1));

        jpboli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jpboli, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 250, 40));

        jpid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 250, 40));

        jpnume.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jpnume, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 250, 40));

        jpadresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jpadresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 250, 40));

        jptelefon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jptelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 250, 40));

        jpvarsta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jpvarsta, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 250, 40));

        jpgrupas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jpgrupas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 250, 40));

        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculin", "Feminin" }));
        jPanel2.add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 250, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 750, 250));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("VIZUALIZARE/MODIFICARE PACIENTI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 480, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\DOWNLOAD_OFFICIAL\\Aplicatie_pt_examen\\Images\\2.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
                DefaultTableModel RecordTable = (DefaultTableModel) tabel.getModel();

//        try
//        {
//            db.fillTable(tabel,"select * from inregistrare_pacient");
//        }
//        catch(Exception ex){
//            JOptionPane.showMessageDialog(null,"Eroare");
//        }
    }//GEN-LAST:event_formWindowActivated

    private void inapoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inapoiActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Acasa().setVisible(true);
    }//GEN-LAST:event_inapoiActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Printare in progress");
        MessageFormat footer = new MessageFormat("Pagina {0,number,integer}");
        try{
            tabel.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e){
            System.err.format("Nu e gasit printer",e.getMessage());
        }
        
    }//GEN-LAST:event_PrintActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        jpid.setText("");
        jpnume.setText("");
        jpadresa.setText("");
        jptelefon.setText("");
        jpvarsta.setText("");
        jpgrupas.setText("");
        jpboli.setText("");
        
    }//GEN-LAST:event_ResetActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        try
        {
                  Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn=DriverManager.getConnection(dataConn,username,password);
            
            pst = sqlConn.prepareStatement("update inregistrare_pacient set pnume = ?, padresa=?,ptelefon=?,pvarsta=?,psex=?,pgrupas=?,pboli=?  where Pid = ?");
            
            
            pst.setString(1,jpnume.getText());
            pst.setString(2,jpadresa.getText());
            pst.setString(3,jptelefon.getText());
            pst.setString(4,jpvarsta.getText());
            pst.setString(5,(String) sex.getSelectedItem());
            pst.setString(6,jpgrupas.getText());
            pst.setString(7,jpboli.getText());
            pst.setString(8,jpid.getText());
            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Inregistrare updatata");
            upDateDB();
            
        }catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this,"Error 404");
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel) tabel.getModel();
        int SelectedRows =tabel.getSelectedRow();
        
        jpid.setText(RecordTable.getValueAt(SelectedRows,0).toString());
        jpnume.setText(RecordTable.getValueAt(SelectedRows,1).toString());
        jpadresa.setText(RecordTable.getValueAt(SelectedRows,2).toString());
        jptelefon.setText(RecordTable.getValueAt(SelectedRows,3).toString());
        jpvarsta.setText(RecordTable.getValueAt(SelectedRows,4).toString());
//        aici posibil neto
        sex.setSelectedItem(RecordTable.getValueAt(SelectedRows,5).toString());
        jpgrupas.setText(RecordTable.getValueAt(SelectedRows,6).toString());
        jpboli.setText(RecordTable.getValueAt(SelectedRows,7).toString());
    }//GEN-LAST:event_tabelMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel RecordTable = (DefaultTableModel) tabel.getModel();
        int SelectedRows =tabel.getSelectedRow();
        try{
            id=Integer.parseInt(RecordTable.getValueAt(SelectedRows,0).toString());
            deleteItem = JOptionPane.showConfirmDialog(null,"Confirmi ca vrei sa stergi inregisrarea?","WARNING",JOptionPane.YES_NO_OPTION);
            if(deleteItem==JOptionPane.YES_OPTION)
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                sqlConn=DriverManager.getConnection(dataConn,username,password);
            pst=sqlConn.prepareStatement("delete from inregistrare_pacient where Pid=?");
            pst.setInt(1,id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Stergere efectuata");
            upDateDB();
            
        jpid.setText("");
        jpid.requestFocus();
        jpnume.setText("");
        jpadresa.setText("");
        jptelefon.setText("");
        jpvarsta.setText("");
        jpgrupas.setText("");
        jpboli.setText("");
            }
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(this,"eroare stergere");
        }
        
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vizualizare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vizualizare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vizualizare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vizualizare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vizualizare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Print;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Update;
    private javax.swing.JButton inapoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jpadresa;
    private javax.swing.JTextField jpboli;
    private javax.swing.JTextField jpgrupas;
    private javax.swing.JTextField jpid;
    private javax.swing.JTextField jpnume;
    private javax.swing.JTextField jptelefon;
    private javax.swing.JTextField jpvarsta;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
